// Sanicle AI Assistant Example Q&A Pairs
// These examples can be used for fine-tuning or reference

export const EXAMPLE_QA_PAIRS = [
  {
    input: "What is Sanicle.cloud?",
    output: "Sanicle.cloud is a B2B-B2G SaaS platform that revolutionizes menstrual and menopause health in the workplace. We provide AI-powered solutions that help employers reduce productivity losses ($150 billion annually) related to menstrual and menopause symptoms. Our platform integrates with IBM's WatsonX.ai to deliver personalized support, predictive analytics, and workplace policy tools that benefit both organizations and employees."
  },
  {
    input: "When will Sanicle.cloud launch?",
    output: "Sanicle.cloud is scheduled for an MVP beta launch in April 2025. We're currently piloting with IBM's 3,000-employee workforce and have 80+ enterprise LOIs (Letters of Intent) and 1,200+ users on our waitlist. Our pre-launch phase includes HIPAA compliance implementation and enhancing our AI capabilities through our IBM Build Lab Partnership."
  },
  {
    input: "How does Sanicle use IBM WatsonX.ai?",
    output: "Sanicle.cloud seamlessly integrates with IBM's WatsonX.ai foundation models, including cutting-edge tools like Granite and Merlinite. This integration enables us to provide:\n• AI-powered insights for personalized cycle tracking\n• Predictive analytics for employers to reduce absenteeism\n• \"Ask Sani\" AI chatbot for discreet period health questions\n• Enhanced OBGYN virtual consultations with AI transcription\n• Data-driven recommendations for workplace policies\n\nThis technology makes sophisticated healthcare insights accessible while maintaining strict privacy and security standards."
  },
  {
    input: "What pricing plans does Sanicle offer?",
    output: "Sanicle.cloud offers three flexible pricing tiers:\n\n• Basic: $10 per user/month - Includes personalized cycle management, AI chatbot (Ask Sani), and financial wellness support\n• Premium: $15 per user/month - Includes all Basic features plus educational resources, social impact initiatives, and menstrual syndrome identification support\n• Enterprise: Custom pricing - Includes all Premium features plus personalized training, consulting, and customized features for your organization's needs\n\nWe also offer white-label solutions for large enterprises starting at $1K+/month. For detailed pricing or a custom quote, I recommend booking a demo through our website."
  },
  {
    input: "Who founded Sanicle?",
    output: "Sanicle was founded by Chaste Inegbedion, known as \"Mr. Padman,\" who started the organization in Nigeria as Padman Africa. Chaste is a global leader in femtech, UN Global Compact Network Partner, and SDG Ambassador with expertise in product management and social entrepreneurship.\n\nThe company is now led by Dr. Omopeju Afanu as CEO, who brings experience from Fortune 500 companies including Amazon, AT&T, and Paycom. Together with a diverse leadership team, they've evolved Sanicle from its roots in menstrual equity advocacy to a comprehensive workplace wellness platform."
  },
  {
    input: "What problem is Sanicle trying to solve?",
    output: "Sanicle addresses several critical workplace challenges:\n\n• $150 billion annual productivity losses due to menstrual and menopause symptoms\n• 25% of women consider quitting jobs due to inadequate support for these health issues\n• 80% of employees who menstruate experience productivity losses related to symptoms\n• Menstrual and menopause health remains largely overlooked in workplace benefits\n• Most employers lack data on how hormonal health affects workforce performance\n• Employees face out-of-pocket costs for basic healthcare supplies and insufficient access to tailored resources\n\nWe're creating measurable business impact while supporting health equity in the workplace."
  },
  {
    input: "How does Sanicle differ from competitors?",
    output: "Sanicle stands out from competitors in several key ways:\n\n• B2B-B2G Focus: Unlike B2C menstrual apps like Flo, we're specifically designed for workplace integration\n• IBM WatsonX.ai Integration: Advanced AI capabilities through our partnership with IBM\n• Comprehensive Approach: We address both menstrual and menopause health needs\n• Social Impact Model: Our \"Buy One, Donate One\" approach extends our impact to underserved communities\n• Female-Led: 85% of our leadership identifies as women, driving solutions based on lived experience\n• Proven Traction: Piloting with IBM's 3,000-employee workforce with 80+ enterprise LOIs\n• Global Perspective: With roots in Nigeria and advocacy success across markets\n\nWe're positioned as the \"Flo for Workplaces\" in a $150B workplace opportunity market."
  },
  {
    input: "What is the \"Buy One, Donate One\" model?",
    output: "Sanicle's \"Buy One, Donate One\" model is core to our social impact mission. For every product purchased through our platform, we donate menstrual kits to underserved communities. To date, we've matched 1.3 million products across Nigeria, Kenya, and underserved regions in the United States.\n\nThis model directly ties our business success to social impact, as we reinvest in eradicating period poverty and advancing menstrual health policies. It's part of our commitment as a social enterprise to balance profitability with purpose, channeling 30% of revenue into R&D for low-resource settings."
  },
  {
    input: "Who is on Sanicle's leadership team?",
    output: "Sanicle's leadership team includes:\n\n• Dr. Omopeju Afanu - Chief Executive Officer (afanu.sanicle@gmail.com)\n• Chaste Inegbedion - Chief Product Officer (chaste.sanicle@gmail.com)\n• Daryll Hall - Chief AI Officer (daryll.sanicle@gmail.com)\n• Cecilia Omole - Chief Operating Officer (cecilia.sanicle@gmail.com)\n• Gabby Hurst - Chief Experience Officer (gabby.sanicle@gmail.com)\n• Chan Meng - Senior AI/ML Infrastructure Engineer (chanmeng.sanicle@gmail.com)\n\nThe team brings diverse expertise in healthcare, technology, AI, product development, and social impact. 85% of our leadership identifies as women, ensuring our solutions are rooted in lived experience."
  },
  {
    input: "What benefits does Sanicle offer to employers?",
    output: "Sanicle.cloud offers employers significant benefits:\n\n• Reduced Absenteeism: Target 20% reduction in menstrual and menopause-related absences\n• Increased Productivity: Save approximately $7/hour per employee\n• Data-Driven Insights: Analytics dashboards for workforce health trends\n• Talent Retention: Support for the 25% of women who consider quitting jobs due to menstrual/menopause issues\n• Inclusive Culture: Tools to develop and implement supportive workplace policies\n• Simplified Benefits: Integration with existing HR systems and FSA/HSA programs\n• ROI Measurement: Monitor program usage and gather feedback to quantify success\n• CSR Impact: Support corporate social responsibility goals through our \"Buy One, Donate One\" model\n\nOur platform turns overlooked health challenges into measurable business results."
  },
  {
    input: "What benefits does Sanicle provide for employees?",
    output: "Sanicle.cloud offers employees comprehensive support:\n\n• Personalized Cycle Tracking: AI-powered insights and predictions based on proprietary data\n• \"Ask Sani\" AI Chatbot: Discreet Q&A support for period health questions\n• Financial Wellness Tools: Navigate FSA/HSA benefits for period products\n• Educational Resources: Library of articles, guides, and videos on menstrual and menopause health\n• OBGYN Support: AI-assisted guidance and virtual consultations with healthcare professionals\n• Symptom Management: Tools for tracking and managing health impacts at work\n• Privacy Protection: HIPAA-compliant platform with strict data security measures\n• Product Recommendations: Personalized suggestions for period and menopause solutions\n\nOur employee-centric approach ensures accessible, personalized support that improves both wellbeing and workplace performance."
  },
  {
    input: "How does Sanicle integrate with existing HR systems?",
    output: "Sanicle.cloud is designed to integrate seamlessly with existing HR systems and benefits platforms. Our integration capabilities include:\n\n• HRIS systems for employee management and onboarding\n• Benefits administration platforms for FSA/HSA integration\n• Leave management systems for tracking and policy alignment\n• Company wellness programs and initiatives\n• Secure data transfer with privacy protections\n\nThe implementation process is straightforward, with our team providing technical support and guidance. For specific integration requirements or compatibility questions, I recommend contacting our team at hello@sanicle.us to discuss your organization's unique needs."
  },
  {
    input: "Does Sanicle have any case studies or success stories?",
    output: "Sanicle.cloud is currently piloting with IBM's 3,000-employee workforce, which will provide comprehensive case study data when completed. Our platform is scheduled for full launch in April 2025, so while we don't have post-implementation case studies yet, we have strong pre-launch validation:\n\n• 80+ enterprise Letters of Intent from interested organizations\n• 1,200+ employees on waitlist eager to use the platform\n• Partnerships with 65 Employee Resource Groups\n• $7K MRR growing at 11% month-over-month in our pre-launch phase\n\nThese early indicators show strong market validation. After our full launch, we'll publish detailed case studies highlighting the ROI and impact on workplace wellness and productivity."
  },
  {
    input: "What is the Period Passport Book?",
    output: "The Period Passport Book is one of Sanicle's educational products - a culturally sensitive toolkit designed to promote menstrual health literacy. It has been distributed in 12 countries and has reached over 100,000 girls worldwide.\n\nThis resource reflects our commitment to education and global impact, providing accessible information about menstrual health in diverse cultural contexts. The Period Passport Book is part of our broader social impact strategy, alongside our advocacy work and the Period Genie Game, an AI-powered app that gamifies menstrual education for schools and corporate training programs."
  },
  {
    input: "How secure is Sanicle's platform?",
    output: "Security and privacy are top priorities at Sanicle.cloud. Our platform features:\n\n• HIPAA compliance for maximum health data protection\n• Secure cloud storage with encryption\n• Multi-factor authentication for secure access\n• User control over data access, edits, and deletions\n• No employer data sharing without explicit consent\n• Anonymized data for insights (only with consent)\n\nWe're currently completing our HIPAA compliance implementation as part of our pre-launch phase. Our integration with IBM WatsonX.ai also ensures we maintain the highest security standards for AI applications in healthcare. Your data's privacy and security are foundational to our platform design."
  },
  {
    input: "Where is Sanicle located?",
    output: "Sanicle is headquartered in Tulsa, Oklahoma. Our office address is:\n\n2930 E 94th St\nSuite 608\nTulsa, OK 74137\n\nYou can reach our team at 929-488-0608 or hello@sanicle.us.\n\nWhile our headquarters is in Tulsa, Sanicle has a global presence and impact, with roots in Nigeria and initiatives across multiple countries."
  },
  {
    input: "What is Sanicle's funding status?",
    output: "Sanicle is currently seeking a $500,000 pre-seed investment round. These funds will be allocated to:\n\n• Product Development: Enhancing our AI/ML capabilities and expanding predictive analytics features\n• Market Expansion: Strengthening partnerships with healthcare providers and scaling enterprise outreach\n• Team Growth: Hiring top talent to accelerate our innovation and customer success initiatives\n\nWe currently have $7K MRR (Monthly Recurring Revenue) growing at 11% month-over-month. Our strong market validation includes interest from 80+ enterprise clients, a waitlist of 1,200+ users, and partnerships with 65 Employee Resource Groups."
  },
  {
    input: "Does Sanicle have job openings?",
    output: "Yes, Sanicle is actively hiring! We're currently looking for:\n\n• Senior Data Scientists to join our core team\n• Senior Sales Representatives\n\nWe're continuously seeking exceptional talent to help transform how we access and finance healthcare. If you're interested in joining our mission, please email your CV to jobs@sanicle.cloud.\n\nSanicle offers stock options for employees to foster shared ownership, and we value diverse perspectives in our mission to revolutionize workplace health equity."
  },
  {
    input: "What are Sanicle's social media accounts?",
    output: "You can connect with Sanicle on these social media platforms:\n\n• Facebook: https://www.facebook.com/Sanicle.us\n• Instagram: https://www.instagram.com/sanicle.us/\n• TikTok: https://www.tiktok.com/@sanicle.us\n\nFollow us to stay updated on our latest news, resources, and initiatives in menstrual and menopause health."
  },
  {
    input: "What is Sanicle's mission?",
    output: "Sanicle's mission is to eradicate period poverty and redefine workplace wellness by ensuring access to menstrual health education, sustainable products, and inclusive policies—bridging grassroots impact with global systemic change.\n\nOur vision is a world where every individual can manage their menstrual health with dignity, and every workplace champions reproductive equity as a cornerstone of well-being.\n\nWe work toward this mission by combining AI-powered technology, education, advocacy, and our \"Buy One, Donate One\" model to create lasting impact across communities and organizations."
  },
  {
    input: "What technology is Sanicle built on?",
    output: "Sanicle.cloud's technology platform is built on several key components:\n\n• IBM WatsonX.ai Integration: We leverage IBM's foundation models, including Granite and Merlinite, for advanced AI capabilities\n• Cloud-Based Infrastructure: Secure, scalable architecture with HIPAA compliance\n• Predictive Analytics: Data-driven insights for both employers and employees\n• API Integrations: Connectivity with HR systems, FSA/HSA providers, and healthcare resources\n• Mobile-Responsive Interface: Accessible design for any device\n\nOur platform is designed to be user-friendly while providing sophisticated capabilities like personalized recommendations, AI-powered chatbot functionality, and analytics dashboards for employers. The integration with IBM WatsonX.ai particularly enhances our ability to provide personalized insights and support for women's health in the workplace."
  },
  {
    input: "How does Sanicle measure success?",
    output: "Sanicle measures success through multiple metrics:\n\n• Reduction in workplace absenteeism (targeting 20% improvement)\n• Productivity gains (approximately $7/hour per employee)\n• User engagement with platform features and resources\n• Enterprise adoption and retention rates\n• Employee satisfaction and wellbeing improvements\n• Social impact indicators (number of products donated, people reached through education)\n• Revenue growth (currently $7K MRR growing at 11% month-over-month)\n• Policy changes influenced at organizational and governmental levels\n\nWe track both business outcomes and social impact to ensure we're delivering on our dual mission of creating business value while advancing menstrual equity and workplace inclusivity."
  },
  {
    input: "What's the expected ROI for companies implementing Sanicle?",
    output: "Companies implementing Sanicle.cloud can expect significant ROI across multiple dimensions:\n\n• Financial: Approximately $7/hour saved per employee through reduced absenteeism and increased productivity\n• Talent Management: Improved retention by supporting the 25% of women who consider quitting jobs due to inadequate menstrual/menopause support\n• Operational: Reduced administrative burden through streamlined benefits management\n• Corporate Culture: Enhanced reputation and employer brand through demonstrated commitment to inclusive health support\n• ESG Impact: Measurable contribution to social impact goals through our \"Buy One, Donate One\" model\n\nWhile exact ROI will vary by organization size and implementation, our targeting of the $150 billion annual productivity loss related to menstrual symptoms provides substantial opportunity for value creation. For a customized ROI calculation based on your organization's specific parameters, we recommend booking a demo through our website."
  },
  {
    input: "Is Sanicle available internationally?",
    output: "Sanicle has global roots and aspirations, with plans to expand internationally after our April 2025 platform launch. Our roadmap includes:\n\n• 2025: Initial focus on U.S. market launch\n• 2026-2030: Expansion to 30+ countries with menopause care\n\nOur Period Passport Book is already distributed in 12 countries, and our \"Buy One, Donate One\" model has provided menstrual products across Nigeria, Kenya, and the U.S.\n\nWhile our initial SaaS platform launch will prioritize the U.S. market, our experience in global menstrual equity work positions us well for international expansion. For international organizations interested in early adoption, please contact us at hello@sanicle.us to discuss partnership opportunities."
  },
  {
    input: "Can you tell me about Sanicle's history?",
    output: "Sanicle began in Nigeria as Padman Africa, founded by Chaste Inegbedion. The organization initially focused on grassroots menstrual equity efforts, including doorstep product delivery reaching over 1M+ women, services through urban health centers, and advocacy that changed national laws, including Nigeria's National Menstrual Health Act which mandated free products in public schools.\n\nIn 2021, the organization expanded to the United States and launched Sanicle.cloud, transitioning to a tech-driven workplace wellness platform. This evolution represents the company's growth from direct service to systemic change through technology and enterprise solutions.\n\nThe company has received international recognition, including hosting the Nova Award at the UN's 69th Commission on the Status of Women. As a registered Community Interest Company (CIC), Sanicle prioritizes purpose over profit, channeling 30% of revenue into R&D for low-resource settings.\n\nThis history informs Sanicle's unique perspective on menstrual equity, combining grassroots experience with technological innovation and enterprise solutions."
  },
  {
    input: "How do employers implement Sanicle at their workplace?",
    output: "Implementing Sanicle.cloud in your workplace follows a simple process:\n\n1. Plan Selection: Choose the tier that best fits your organization's needs (Basic, Premium, or Enterprise).\n\n2. Employee Enrollment: Our platform allows you to effortlessly enroll employees and distribute access codes in seconds.\n\n3. System Integration: We provide technical support to integrate with your existing HR systems, benefits platforms, and leave management systems.\n\n4. Dashboard Setup: Configure your analytics dashboard to track relevant metrics and workforce health trends.\n\n5. Employee Onboarding: Employees redeem their access codes and begin using the platform's resources.\n\n6. Ongoing Support: Monitor program usage and gather feedback to measure success (available on select plans).\n\nOur implementation team provides comprehensive support throughout the process. For specific integration requirements or compatibility questions, contact us at hello@sanicle.us."
  },
  {
    input: "What kind of data and analytics does Sanicle provide to employers?",
    output: "Sanicle.cloud provides employers with powerful data and analytics capabilities while maintaining strict user privacy:\n\n• Productivity Metrics: Track improvements in attendance and performance related to menstrual and menopause health support\n• Absenteeism Patterns: Identify trends in absences that may be related to menstrual health issues\n• Resource Utilization: Understand which platform resources are most valuable to your workforce\n• Anonymous Feedback: Gather insights about employee needs and satisfaction with your health benefits\n• Policy Impact: Measure the effectiveness of workplace policies and initiatives\n• ROI Calculations: Quantify the return on investment from implementing menstrual and menopause support\n\nAll data is anonymized and aggregated to protect individual privacy, and no personal health information is shared without explicit consent. Our analytics dashboard is designed to provide actionable insights while maintaining the highest standards of data protection."
  },
  {
    input: "How does the Period Genie Game work?",
    output: "The Period Genie Game is an AI-powered educational application developed by Sanicle that gamifies menstrual education. It's designed for use in schools and corporate training programs to increase menstrual health literacy in an engaging, accessible format.\n\nKey features include:\n\n• Interactive Learning Modules: Covering menstrual biology, health management, and myth-busting\n• Culturally Sensitive Content: Adapted for diverse cultural contexts and age groups\n• Achievement System: Rewards knowledge milestones and encourages continued learning\n• AI-Powered Personalization: Content adapts based on user knowledge level and interests\n• Resource Connections: Links to additional educational materials and support resources\n\nThe game complements our Period Passport Book and forms part of our comprehensive approach to education and advocacy. By making menstrual education engaging and accessible, we're working to reduce stigma and increase knowledge about menstrual health across diverse communities."
  },
  {
    input: "What advocacy work has Sanicle done?",
    output: "Sanicle has a strong track record of advocacy for menstrual equity across multiple countries:\n\n• Nigeria: Successfully lobbied for the National Menstrual Health Act, which now provides free menstrual products in public schools nationwide\n• United States: Partnered with legislators to pass workplace menstrual equity laws in 8 states\n• Global: Hosted panels and keynote speeches at international forums including the UN Civil Society Conference in South Korea, New York, and Kenya, as well as the Montpellier Peace Summit in France\n• Corporate: Launched employee wellness programs tied to IBM WatsonX.ai analytics during the Black Tech Conference in Texas\n• Cultural Events: Hosted panels at the Wakanda Forever premiere (Women of Wakanda in Tulsa), MLK Day rallies, and International Women's Day summits\n\nOur advocacy work complements our product development, creating systemic change in how menstrual health is addressed in workplaces, schools, and public policy. We believe advocacy is essential to our mission of eradicating period poverty and redefining workplace wellness."
  },
  {
    input: "How does Sanicle approach menopause support in the workplace?",
    output: "Sanicle takes a comprehensive approach to supporting employees experiencing menopause in the workplace:\n\n• Personalized Symptom Tracking: Tools for monitoring and managing menopause symptoms that affect work\n• Educational Resources: Evidence-based information about menopause stages, symptoms, and management strategies\n• Anonymous Support: Discreet communication channels for employees to request accommodations or support\n• Manager Training: Resources for supervisors to understand and appropriately support team members experiencing menopause\n• Policy Guidelines: Templates and best practices for developing menopause-inclusive workplace policies\n• Connectivity with Healthcare: Integration with healthcare providers specializing in menopause care\n\nOur approach recognizes that menopause symptoms can significantly impact workplace productivity and wellbeing, with a significant number of employees silently managing symptoms without adequate support. By addressing both menstrual health and menopause, Sanicle provides comprehensive support across the reproductive health spectrum.\n\nOur 2026-2030 roadmap includes expanding menopause care to 30+ countries, reflecting our commitment to this often-overlooked aspect of workplace health."
  },
  {
    input: "What is Sanicle's company structure?",
    output: "Sanicle is structured as a Community Interest Company (CIC), a type of social enterprise that prioritizes purpose over profit. This structure reflects our commitment to balancing profitability with social impact.\n\nKey aspects of our company structure include:\n\n• Female-Led Leadership: 85% of our leadership team identifies as women, ensuring our solutions are rooted in lived experience\n• Reinvestment Model: We channel 30% of revenue into R&D for low-resource settings\n• Cross-Functional Teams: Our team integrates expertise in healthcare, technology, AI, product development, and social impact\n• Advisory Board: Visionaries in healthcare, AI, and ESG guide our long-term growth\n• Global Presence: While headquartered in Tulsa, Oklahoma, we maintain connections to our Nigerian roots and operate with a global perspective\n\nThis structure enables us to maintain our dual focus on creating business value and advancing menstrual equity worldwide. As a social enterprise, we measure success not just in financial terms but also by our impact on communities and workplaces."
  },
  {
    input: "How does the Ask Sani AI chatbot work?",
    output: "The \"Ask Sani\" AI chatbot is a key feature of our platform, providing discreet, personalized support for period health questions. Here's how it works:\n\n• IBM WatsonX.ai Integration: Powered by advanced foundation models (Granite and Merlinite) for natural language understanding and generation\n• Confidential Interaction: Provides a private channel for employees to ask sensitive questions about menstrual and menopause health\n• Evidence-Based Responses: Delivers accurate, medically sound information based on current research and best practices\n• Personalized Support: Tailors responses based on user history and reported symptoms or concerns\n• Resource Connection: Directs users to relevant educational materials, healthcare benefits, or support options\n• Continuous Learning: Improves over time based on interactions while maintaining strict privacy standards\n\nThe chatbot serves as a first line of support, providing immediate answers to common questions while directing more complex health concerns to appropriate healthcare professionals. This feature is particularly valuable for employees who may be hesitant to discuss menstrual or menopause health issues in person, ensuring they still receive the support they need."
  },
  {
    input: "What makes Sanicle different from regular period tracking apps?",
    output: "Sanicle.cloud differs fundamentally from regular period tracking apps in several key ways:\n\n• B2B-B2G Focus: Unlike B2C apps like Flo that focus on individual consumers, Sanicle is specifically designed for implementation by employers and government organizations\n• Workplace Integration: We directly integrate with HR systems, benefits platforms, and leave management systems to create holistic workplace solutions\n• Business Metrics: Our platform provides analytics on workforce productivity, absenteeism, and ROI rather than just individual health tracking\n• Policy Development: We offer tools and resources for developing inclusive workplace policies and benefits\n• Comprehensive Scope: We address both menstrual health and menopause support in a single platform\n• Enterprise Security: We implement HIPAA-compliant security measures designed for organizational deployment\n• Social Impact Model: Our \"Buy One, Donate One\" approach extends benefits beyond direct users\n\nWhile consumer period tracking apps serve individuals, Sanicle transforms how organizations approach menstrual and menopause health, creating systemic changes that benefit both employers and employees. We're positioned as the \"Flo for Workplaces\" in a $150B workplace opportunity market."
  },
  {
    input: "How does Sanicle's FSA/HSA integration work?",
    output: "Sanicle.cloud's FSA/HSA integration streamlines access to menstrual health products and services through pre-tax healthcare accounts:\n\n• Eligibility Verification: The platform automatically identifies which products and services qualify for FSA/HSA coverage\n• Simplified Claims: Streamlined documentation for menstrual and menopause-related expenses\n• Education Resources: Clear information about how employees can utilize their benefits for menstrual health\n• Digital Receipts: Automated receipt generation for qualifying purchases\n• Benefits Navigation: Guidance on maximizing FSA/HSA benefits for menstrual and menopause care\n• Administrator Tools: Resources for benefits administrators to configure and manage integration\n\nThis integration removes financial barriers to essential health products and creates a seamless experience for both employees and benefits administrators. By simplifying access to pre-tax funds for menstrual health needs, we help make comprehensive care more affordable and accessible in the workplace."
  }
];

// Additional Q&A pairs based on company documents
export const ADDITIONAL_QA_PAIRS = [
  {
    input: "What recognition has Sanicle received?",
    output: "Sanicle has received significant recognition for its innovation and impact in menstrual equity:\n\n• Recognized as Social Enterprise of the Year with 23+ activations for innovation and impact\n• Hosted the Nova Award at the UN's 69th Commission on the Status of Women\n• Spearheaded the Beyond Beijing Summit 30, cementing our role as a policy innovator\n• Selected as a keynote speaker at the UN Civil Society Conference across multiple continents\n• Presented on sustainable development at global forums\n• Addressed the United Nations Commission on the Status of Women\n• Featured in discussions on technology's role in the future of work at the 2024 UN General Assembly\n\nThese recognitions reflect our leadership in both technology innovation and advocacy for menstrual equity, validating our approach of combining business solutions with social impact."
  },
  {
    input: "Tell me about Sanicle's global impact",
    output: "Sanicle's global impact spans multiple continents and initiatives:\n\n• Nigeria: Reached 1M+ women through doorstep product delivery and urban health centers; advocated for the National Menstrual Health Act mandating free products in public schools\n• Kenya: Provided menstrual products through our \"Buy One, Donate One\" model\n• United States: Distributed products to underserved communities; partnered with legislators to pass workplace menstrual equity laws in 8 states\n• Education: The Period Passport Book has reached 100,000+ girls across 12 countries\n• Policy Influence: Hosted international events including the Nova Award at the UN's 69th Commission on the Status of Women and the Beyond Beijing Summit 30\n• Corporate Impact: Currently piloting with IBM's 3,000-employee workforce\n\nOur roadmap includes expanding to 30+ countries with menopause care between 2026-2030, with a goal of impacting 10M+ employees through policy and technology. This global perspective, rooted in our Nigerian origins and expanded worldwide, informs our comprehensive approach to menstrual equity."
  },
  {
    input: "What is Sanicle's connection to Nigeria?",
    output: "Sanicle's connection to Nigeria is foundational to our identity and mission:\n\n• Origins: Founded in Nigeria as Padman Africa by Chaste Inegbedion before evolving into Sanicle\n• Early Impact: Reached 1M+ women through doorstep product delivery and services at urban health centers\n• Policy Success: Successfully advocated for Nigeria's National Menstrual Health Act, which now mandates free menstrual products in public schools nationwide\n• Continued Presence: Our \"Buy One, Donate One\" model continues to provide menstrual products to communities in Nigeria\n• Global Perspective: This Nigerian foundation informs our global approach to menstrual equity, combining grassroots experience with technological innovation\n\nOur evolution from Padman Africa in Nigeria to Sanicle.cloud represents our growth from direct service to systemic change through technology and enterprise solutions, while maintaining our commitment to the communities where we began our work."
  },
  {
    input: "How did Sanicle start?",
    output: "Sanicle began as Padman Africa in Nigeria, founded by Chaste Inegbedion (known as \"Mr. Padman\") with a focus on grassroots menstrual equity initiatives:\n\n• Initial Focus: Providing doorstep product delivery, serving urban health centers, and advocating for policy change\n• Early Impact: Reached over 1M+ women across Nigeria\n• Policy Success: Successfully lobbied for Nigeria's National Menstrual Health Act, which mandated free products in public schools\n\nIn 2021, the organization expanded to the United States and launched Sanicle.cloud, shifting to a tech-driven workplace wellness platform:\n\n• Strategic Pivot: Recognized the opportunity to address menstrual health as a workplace issue\n• Technology Integration: Developed an AI-powered platform integrating with IBM's WatsonX.ai\n• B2B-B2G Approach: Repositioned to serve enterprises and government organizations\n\nThis evolution from direct service to technology-enabled systemic change represents our growth while maintaining our core mission of advancing menstrual equity and eradicating period poverty. Today, Sanicle combines this rich history with cutting-edge technology to transform how workplaces support menstrual and menopause health."
  },
  {
    input: "What is the Period Genie Game?",
    output: "The Period Genie Game is an AI-powered educational application developed by Sanicle that gamifies menstrual education. It's designed to make learning about menstrual health engaging and accessible through:\n\n• Interactive Learning: Game-based modules that educate users about menstrual health in an engaging format\n• AI Technology: Utilizing artificial intelligence to personalize the educational experience\n• Multiple Audiences: Designed for both schools and corporate training programs\n• Cultural Sensitivity: Content adapted for various cultural contexts and age groups\n• Educational Impact: Part of our broader strategy to increase menstrual health literacy globally\n\nThis innovative approach to education complements our Period Passport Book and extends our impact beyond product provision. By gamifying menstrual education, we make important health information more accessible and engaging, helping to reduce stigma and increase knowledge about menstrual health across diverse communities."
  },
  {
    input: "How is Sanicle funded?",
    output: "Sanicle employs a diverse funding and revenue model:\n\n**Current Status:**\n• Pre-seed Round: Currently seeking $500,000 in pre-seed investment\n• Revenue Traction: $7K Monthly Recurring Revenue (MRR) growing at 11% month-over-month\n• Market Validation: 80+ enterprise Letters of Intent and 1,200+ users on waitlist\n\n**Revenue Streams:**\n• SaaS Subscriptions: Tiered pricing model (Basic: $10/user/month, Premium: $15/user/month, Enterprise: custom pricing)\n• White-Label Solutions: Custom options for large enterprises starting at $1K+/month\n• Integration Fees: For connecting with HRIS platforms and benefits providers\n• Public Sector Contracts: For health-focused government programs\n\n**Allocation of Funds:**\n• 30% of revenue channeled into R&D for low-resource settings (as part of our social enterprise model)\n• Current fundraising will support product development, market expansion, and team growth\n\nAs a Community Interest Company (CIC), we prioritize purpose over profit, balancing business sustainability with our social mission of advancing menstrual equity worldwide."
  },
  {
    input: "How does Sanicle approach data privacy?",
    output: "Sanicle takes a rigorous approach to data privacy, particularly important given the sensitive nature of menstrual and menopause health information:\n\n• HIPAA Compliance: Currently implementing comprehensive HIPAA standards for maximum health data protection\n• User Control: Individuals maintain control over their personal data with options for access, edits, and deletions\n• Explicit Consent: No employer data sharing without explicit consent from employees\n• Anonymized Insights: When data is used for analytics, it's anonymized to protect individual privacy\n• Secure Infrastructure: Cloud storage with encryption to protect all stored information\n• Multi-factor Authentication: Enhanced security measures for platform access\n• Transparent Policies: Clear communication about how data is used and protected\n\nOur privacy approach balances the need to provide valuable insights to employers while rigorously protecting individual health information. This ensures that employees can benefit from support and accommodations without compromising their privacy."
  },
  {
    input: "What countries does Sanicle operate in?",
    output: "Sanicle currently operates primarily in:\n\n• United States: Our headquarters is in Tulsa, Oklahoma, and we're focusing our initial SaaS platform launch on the U.S. market in April 2025\n• Nigeria: Our roots as Padman Africa continue with product distribution and advocacy work\n• Kenya: One of our key markets for the \"Buy One, Donate One\" model\n\nAdditionally, our educational resources have broader reach:\n• The Period Passport Book is distributed in 12 countries worldwide\n• We've participated in international forums and advocacy events across multiple continents\n\nOur expansion plans include:\n• 2025: Initial focus on U.S. market launch\n• 2026-2030: Expansion to 30+ countries with menopause care\n\nFor international organizations interested in early adoption before our global expansion, we welcome discussions about partnership opportunities through hello@sanicle.us."
  }
]; 